# Generated by Django 2.2.19 on 2023-10-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231011_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipe',
            new_name='favorite_recipe',
        ),
    ]
