# Generated by Django 4.2.4 on 2023-10-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_follow_check_follow_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_unique_constraint',
        ),
    ]
