# Generated by Django 2.2.19 on 2023-10-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231017_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='favorite_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
