version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../foodgram/
    env_file:
      - ../.env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/
  gateway:
    build: ../nginx/
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/